const mockMealsName = { // pesquisa referente ao nome do prato sendo Garlic
  meals: [
    {
      idMeal: '52815',
      strMeal: 'French Lentils With Garlic and Thyme',
      strDrinkAlternate: null,
      strCategory: 'Miscellaneous',
      strArea: 'French',
      // strInstructions: 'Place a large saucepan over medium heat and add oil. When hot, add chopped vegetables and sauté until softened, 5 to 10 minutes.\r\nAdd 6 cups water, lentils, thyme, bay leaves and salt. Bring to a boil, then reduce to a fast simmer.\r\nSimmer lentils until they are tender and have absorbed most of the water, 20 to 25 minutes. If necessary, drain any excess water after lentils have cooked. Serve immediately, or allow them to cool and reheat later.\r\nFor a fuller taste, use some chicken stock and reduce the water by the same amount.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/vwwspt1487394060.jpg',
      strTags: 'Pulse',
      strYoutube: 'https://www.youtube.com/watch?v=CrlTS1mJQMA',
      strIngredient1: 'Olive Oil',
      strIngredient2: 'Onion',
      strIngredient3: 'Garlic',
      strIngredient4: 'Carrot',
      strIngredient5: 'French Lentils',
      strIngredient6: 'Thyme',
      strIngredient7: 'Bay Leaf',
      strIngredient8: 'Salt',
      strIngredient9: 'Celery',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '3 tablespoons',
      strMeasure2: '1',
      strMeasure3: '2 cloves',
      strMeasure4: '1',
      strMeasure5: '2 1/4 cups',
      strMeasure6: '1 teaspoon',
      strMeasure7: '3',
      strMeasure8: '1 tablespoon',
      strMeasure9: '2 sticks',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: '',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};
export default mockMealsName;
